### PR TITLE
Add the UMN block M to the QR code

### LINKED ISSUE #146: Brand QR code with Block M
Feature request: https://tdx.umn.edu/TDNext/Apps/29/Tickets/TicketDet.aspx?TicketID=1196246

### PR DESCRIPTION
**Pull request by jxjj**
This brands the QR codes generated by Z:
- add a block M in the center
- colors the code UMN maroon

Barby is dropped as a dependency and we're using rqrcode directly for generation. To do the overlay work,  [minimagick](https://github.com/minimagick/minimagick) is added a dependency. See https://github.com/whomwah/rqrcode/issues/91

qrcode example

On https://cla-z-dev.oit.umn.edu for testing.

Resolves #146

### CODE REVIEW

**Review by cmcfadden — COMMENTED** [review]
I think better to stick with black - most folks who use QR codes aren't going to be tech savvy about re-coloring, and black is going to be a more universal fit for documents, printing, etc. 

It seems like this adds a dependency on imagemagick being installed on the system, which isn't generally true of Z hosts - it seems to be installed on the dev/stage hosts, because OIT must have included it by default at one point, but it's not included on our new production hosts. We can definitely add that, but that'll make this deployment more complicated and we'll need to track that. Maybe something to keep on the shelf to include with a future round of updates?

**Comment by cmcfadden** [comment]
Actually, thinking about this more, I'm not sure we should move forward with this, at least as a default.

Z links aren't university blessed, and I'm worried that attaching the official branding to any random student produced item might convey a legitimacy that would rub some folks the wrong way. Minimally, we should get some more feedback and talk through the risks.

**Comment by cmcfadden** [comment]
Also, good use of a rick roll.

**Comment by jxjj** [comment]
Changed to black:
z-rate123

One option is to only generate M branded links for zlinks that resolve to `*.umn.edu` urls.  I'm also fine with parking or closing this or following up with folks (if you let me know who).

**Comment by cmcfadden** [comment]
close this so we don't get in trouble with the brand police

**Pull request closed without merging**
